blank_issues_enabled: false
contact_links:
  - name: Техническая поддержка / Tech support (Telegram)
    url: https://t.me/alryaz_ha_addons
    about: Пожалуйста, задавайте вопросы об интеграции тут.
